#!/bin/bash

case $- in
    *i*) ;;
      *) return;;
esac

export PATH="\
/bin:\
/sbin:\
/usr/bin:\
/usr/local/bin:\
/usr/local/sbin:\
/usr/sbin:\
/var/lib/flatpak/exports/bin:\
${HOME}/.local/bin:\
${HOME}/.local/share/flatpak/exports/bin:\
${HOME}/.scripts"

export BROWSER=brave-browser
export EDITOR=edit
export SUDO_EDITOR=edit
export HISTCONTROL=ignoreboth
export HISTFILESIZE=2000
export HISTSIZE=1000
export LESS="-F -g -i -M -R -S -w -z-6 -X"
export PAGER=less
export PS1="\[\e[90m\] \w\[\e[0m\] > "
force_color_prompt=yes
shopt -s checkwinsize
shopt -s histappend

if ! shopt -oq posix; then
    if [[ -f /usr/share/bash-completion/bash_completion ]]; then
        source /usr/share/bash-completion/bash_completion
    elif [[ -f /etc/bash_completion ]]; then
        source /etc/bash_completion
    fi
fi
