#!/bin/bash

if [[ "${PWD}" != "${HOME}/dotfiles" ]]; then
	echo "Run this script from '${HOME}/dotfiles'"
	exit 1
fi

paths_to_remove=(
	"${HOME}/.bash_profile"
	"${HOME}/.bashrc"
	"${HOME}/.config/bspwm"
	"${HOME}/.config/easyeffects"
	"${HOME}/.config/hypr"
	"${HOME}/.config/mpd"
	"${HOME}/.config/mpv"
	"${HOME}/.config/ncmpcpp"
	"${HOME}/.config/polybar"
	"${HOME}/.config/rofi"
	"${HOME}/.config/sxhkd"
	"${HOME}/.config/topgrade.d"
	"${HOME}/.config/waybar"
	"${HOME}/.profile"
	"${HOME}/.scripts"
	"${HOME}/.source"
	"${HOME}/.xinitrc"
)

for path_to_remove in "${paths_to_remove[@]}"; do
	if [[ -e "${path_to_remove}" && ! -L "${path_to_remove}" ]]; then
		echo "Removing '${path_to_remove}'"
		gio trash -f "${path_to_remove}" || catch "Failed to remove '${path_to_remove}'"
	else
		continue
	fi
done

stow .
