#!/bin/bash

catch() { echo "${1}"; exit 1; }

[[ "${PWD}" == "${HOME}/dotfiles" ]] \
|| catch "Run this script from '${HOME}/dotfiles'"

for cmd in trash-put stow; do
	command -v "${cmd}" 1>/dev/null \
	|| catch "Command not found: '${cmd}'"
done

# these need to be manually added
# needed so the script can make-way for 'stow' command
paths_to_remove=(
	"${HOME}/.bash_profile"
	"${HOME}/.bashrc"
	"${HOME}/.color_schemes.json"
	"${HOME}/.config/bspwm"
	"${HOME}/.config/easyeffects"
	"${HOME}/.config/hypr"
	"${HOME}/.config/mpd"
	"${HOME}/.config/mpv"
	"${HOME}/.config/ncmpcpp"
	"${HOME}/.config/rofi"
	"${HOME}/.config/sxhkd"
	"${HOME}/.profile"
	"${HOME}/.scripts"
	"${HOME}/.source"
	"${HOME}/.walls"
	"${HOME}/.xinitrc"
)

for path_to_remove in "${paths_to_remove[@]}"; do
	if [[ -e "${path_to_remove}" || ! -L "${path_to_remove}" ]]; then
		echo "Moving '${path_to_remove}' to trash"
		trash-put -f "${path_to_remove}" \
		|| catch "Failed to move '${path_to_remove}' to trash"
	else
		continue
	fi
done

stow .
