watch-history-path="~/.config/mpv/play-history"
watch-later-dir="~/.config/mpv/play-later"
ignore-path-in-watch-later-config=yes
resume-playback=no
save-position-on-quit=no
save-watch-history=no
write-filename-in-watch-later-config=yes

hwdec=auto
vo=gpu
force-window=yes
