#!/bin/bash
set -euo pipefail

pacman -Qem &>/dev/null && foreigns_found=yes || foreigns_found=no
command -v yay &>/dev/null && yay_found=yes || yay_found=no
aur_available=yes # ping -qn -c 1 aur.archlinux.org &> /dev/null && aur_available=yes || aur_available=no

if [[ ${foreigns_found} == "yes"  && ${yay_found} == "yes"  && ${aur_available} == "yes"  ]]; then
	exit 0
else
	[[ ${foreigns_found} == "yes" ]] && color="\e[32m" || color="\e[31m"; echo -e "foreigns_found=${color}${foreigns_found}\e[0m" 1>&2
	[[ ${yay_found} == "yes" ]] && color="\e[32m" || color="\e[31m"; echo -e "yay_found=${color}${yay_found}\e[0m" 1>&2
	[[ ${aur_available} == "yes" ]] && color="\e[32m" || color="\e[31m"; echo -e "aur_available=${color}${aur_available}\e[0m" 1>&2
	exit 1
fi
