#!/bin/bash
set -euo pipefail

chkcmd pacman yay

ping -qn -c 1 aur.archlinux.org &> /dev/null || catch -e "Cannot ping AUR"
yay -Sua --noconfirm --cleanafter --ignore gcc14 --ignore gcc14-libs || catch -e "Failed to update AUR packages"