#!/bin/bash
set -euo pipefail

error() {
    echo "${1}" 1>&2
    exit 1
}

info() {
    echo "${1}" 1>&2
    return 0
}

if [[ -z "${1}" || -z "${2}" ]]; then
    echo "Usage: ${0##*/} <-e|-w|-i> <message>"
    exit 1
fi

case "${1}" in
    -e ) error "${2}" ;;
    -i ) info "${2}" ;;
    * ) error "Usage: ${0##*/} <-e|-w|-i> <message>" ;;
esac