#!/bin/bash
set -euo pipefail

error() {
    echo "[ERROR] ${1}" 1>&2
    exit 1
}

warning() {
    echo "[WARNING] ${1}" 1>&2
    return 0
}

info() {
    echo "[INFO] ${1}" 1>&2
    return 0
}

if [[ -z "${1}" || -z "${2}" ]]; then
    echo "Usage: ${0##*/} <-e|-w|-i> <message>"
    exit 1
fi

case "${1}" in
    -e ) error "${2}" ;;
    -w ) warning "${2}" ;;
    -i ) info "${2}" ;;
    * ) error "Usage: ${0##*/} <-e|-w|-i> <message>" ;;
esac