#!/bin/bash

check_command() {
    for cmd in "${@}"; do
        if ! command -v "${cmd}" 1>/dev/null; then
        catch -e "Command '${cmd}' not found. Install to proceed."
        status=1
        fi
    done
    return "${status:-0}"
}

check_command "${@}"