#!/bin/bash
set -euo pipefail

chkcmd trash-put trash-empty

sudo trash-put -fv /tmp/* || catch -e "ROOT: Failed to clean /tmp directory."
trash-put -fv /tmp/* || catch -e "USER: Failed to clean /tmp directory."
sudo trash-empty -fv || catch -e "ROOT: Failed to empty trash."
trash-empty -fv || catch -e "USER: Failed to empty trash."
echo "Syncing..."
sync