#!/bin/bash

error() {
    echo "[ERROR] ${1}" 1>&2
    exit 1
}

warning() {
    echo "[WARNING] ${1}" 1>&2
    return 0
}

confirm() {
    local launcher prompt usage rofi_args
    launcher="${1}"
    prompt="${2}"
    usage="Usage: ${0##*/} <-term|-rofi|-hypr> <prompt>"
    rofi_args=(-dmenu -p "${prompt} (v -_-)>")

    [[ -z "${launcher}" ]] && error "${usage}"
    [[ -z "${prompt}" ]] && error "${usage}"

    case "${launcher}" in
        -term )
            read -p "${prompt} [y/N]: "
            case "${REPLY:-N}" in
                [yY]* ) return 0 ;;
                * ) return 1 ;;
            esac
            ;;
        -rofi ) [[ "$(printf "Yes\nNo" | rofi "${rofi_args[@]}")" == "Yes" ]] || return 1 ;;
        -hypr ) [[ "$(printf "Yes\nNo" | hyprlauncher -p "${prompt}")" == "Yes" ]] || return 1 ;;
        * ) error "Unsupported launcher: ${launcher}" ;;
    esac
}

check_command() {
    command -v "${@}" 1>/dev/null || error "Required command '${*}' not found. Please install it to proceed."
}

select_option() {
    local launcher prompt options usage selection
    launcher="${1}"
    prompt="${2}"
    shift 2
    options=("${@}")
    usage="Usage: ${0##*/} <-term|-rofi|-hypr> <prompt> <options_array>"

    [[ -z "${launcher}" ]] && error "${usage}"
    [[ -z "${prompt}" ]] && error "${usage}"
    (( "${#options[@]}" <= 0 )) && error "${usage}"

    launch_term() {
        PS3="${prompt}"
        select selection in "${options[@]}"; do
            [[ -z "${selection}" ]] && { warning "Invalid selection" && continue; }
            break
        done
    }

    launch_rofi() {
        local rofi_args
        rofi_args=(-dmenu -p "${prompt} (v -_-)>")
        selection="$(printf "%s\n" "${options[@]}" | rofi "${rofi_args[@]}" || error "Failed to get selection from GUI prompt")"
    }

    launch_hypr() {
        selection="$(printf "%s\n" "${options[@]}" | hyprlauncher -p "${prompt}" || error "Failed to get selection from GUI prompt")"
    }

    case "${launcher}" in
        -term ) launch_term ;;
        -rofi ) launch_rofi ;;
        -hypr ) launch_hypr ;;
        * ) error "Unsupported launcher: ${launcher}" ;;
    esac

    echo "${selection}"
}