#!/bin/bash

catch() { echo "${1}"; exit 1; }

for cmd in curl jq; do
    command -v "${cmd}" 1>/dev/null \
    || catch "Command not found: '${cmd}'"
done

get_coordinates() {
    echo "Getting GPS coordinates..."
    coords="$(curl --fail http://ip-api.com/json?fields=lat,lon || true)"
    if [[ -n "${coords}" ]]; then
        latitude=$(echo "${coords}" | jq -r '.lat' || true)
        longitude=$(echo "${coords}" | jq -r '.lon' || true)
        echo "GPS coordinates obtained: ${latitude}, ${longitude}"
        echo -e "${latitude}\n${longitude}" > "${HOME}/.gps_coordinates"
    else
        echo "Failed to get GPS coordinates."
    fi
}

if [[ -f "${HOME}/.gps_coordinates" ]]; then
    echo "GPS coordinates file found. Reading GPS coordinates..."
    { IFS= read -r latitude; IFS= read -r longitude; } < "${HOME}/.gps_coordinates"
    echo "Current GPS coordinates: ${latitude}, ${longitude}"
else
    get_coordinates
fi