#!/bin/bash

brave_dir="${HOME}/.config/BraveSoftware"
if [[ ! -d "${brave_dir}" ]]; then
    echo "Path not found: '${brave_dir}'"
    exit 1
fi

backup_drive="$(lsblk -no mountpoints | grep -si "/STUFF"$ || true)"
if [[ ! -d "${backup_drive}" ]]; then
    echo "Path not found: '${backup_drive}'"
    exit 1
fi

backup_name="BraveSoftware-$(printf "%(%Y-%m-%d)T\n" -1)"
backup_path_base="${backup_drive}/linux"
mkdir -p "${backup_path_base}"
backup_path="${backup_path_base}/${backup_name}"

if [[ -f "${backup_path}" ]]; then
    echo "Backup already exists: '${backup_path}'"
    exit 0
else
    if tar -czvf "${backup_path}" "${brave_dir}"; then
        echo "Backup created: '${backup_path}'"
    else
        echo "Failed to create backup: '${backup_path}'"
        exit 1
    fi
fi