#!/bin/bash

for file in "${HOME}/.scripts"/*; do
    if head -n 1 "${file}" | grep -q '^#!/bin/bash$' && [[ ! -x "${file}" ]]; then
        echo "Making ${file} executable..."
        chmod +x "${file}"
    else
        continue
    fi
done