#!/bin/bash

binary_paths=(
	"/usr/bin/apt-get"
	"/usr/bin/dpkg"
	"/usr/bin/flatpak"
)

for bin_path in "${binary_paths[@]}"; do
	bin_name="${bin_path##*/}"

	if [[ ! -f "${bin_path}" ]]; then
		echo "Binary '${bin_path}' not found" && continue
	fi

	if [[ ! -x "${bin_path}" ]]; then
		echo "Binary '${bin_path}' not executable" && continue
	fi

	if [[ -f /etc/sudoers.d/"${bin_name}" ]]; then
		echo "File already exists '/etc/sudoers.d/${bin_name}'" && continue
	fi

	echo "${USER} ALL=(ALL) NOPASSWD: ${bin_path}" |\
		sudo tee /etc/sudoers.d/"${bin_name}"
	if [[ -f /etc/sudoers.d/"${bin_name}" ]]; then
		sudo chmod 440 /etc/sudoers.d/"${bin_name}"
	else
		echo "Failed to create '/etc/sudoers.d/${bin_name}'" && continue
	fi
done
