#!/bin/bash

catch() { echo "${1}"; exit 1; }

for file in "${HOME}/.scripts"/*; do
    [[ -f "${file}" ]] || continue
    if head -n 1 "${file}" | grep -q '^#!/bin/bash$'; then
        [[ -x "${file}" ]] && continue
        echo "Making ${file} executable..."
        chmod +x "${file}" || catch "Failed to make '${file}' executable."
    fi
done