#!/bin/bash

error() {
    echo "[ERROR] ${1:-Unknown error}" 1>&2
    exit 1
}

warning() {
    echo "[WARNING] ${1:-Unknown warning}" 1>&2
}

confirm() {
    read -p "${1:-Confirm?} [y/N]: "
    case "${REPLY:-N}" in
        [yY]* ) return 0 ;;
        * ) return 1 ;;
    esac
}

check_command() {
    command -v "${@}" 1>/dev/null || error "Required command '${*}' not found. Please install it to proceed."
}

select_option() {
    local launcher prompt options usage selection
    launcher="${1:-term}"
    prompt="${2:-Select an option: }"
    shift 2
    options=("${@}")
    usage="Usage: ${0##*/} <-term|-rofi|-hypr> <prompt> <options_array>"

    [[ -z "${launcher}" ]] && error "${usage}"
    [[ -z "${prompt}" ]] && error "${usage}"
    (( "${#options[@]}" <= 0 )) && error "${usage}"

    launch_term() {
        PS3="${prompt}"
        select selection in "${options[@]}"; do
            [[ -z "${selection}" ]] && { warning "Invalid selection" && continue; }
            break
        done
    }

    launch_rofi() {
        selection="$(printf "%s\n" "${options[@]}" | rofi -dmenu -p "${prompt}" || error "Failed to get selection from GUI prompt")"
    }

    launch_hypr() {
        selection="$(printf "%s\n" "${options[@]}" | hyprlauncher -p "${prompt}" || error "Failed to get selection from GUI prompt")"
    }

    case "${launcher}" in
        -term ) launch_term ;;
        -rofi ) launch_rofi ;;
        -hypr ) launch_hypr ;;
        * ) error "Unsupported launcher: ${launcher}" ;;
    esac
    echo "${selection}"
}