#!/bin/bash

error() { echo "[ERROR] ${1:-Unknown error}" 1>&2; exit 1; }

[[ ${#} -lt 3 ]] && error "Usage: ${0##*/} <launcher> <prompt> <options_array>"

launcher="${1:-term}"
prompt="${2}"
shift 2
options=("${@}")

[[ -z "${prompt}" ]] && error "Prompt cannot be empty"
[[ "${#options[@]}" -eq 0 ]] && error "Options list cannot be empty"

if [[ -t 0 ]]; then
    PS3="${prompt}"
    select selection in "${options[@]}"; do
        [[ -z "${selection}" ]] && echo "Invalid selection" && continue
        break
    done
elif [[ -n "${DISPLAY}" ]]; then
    selection="$(printf "%s\n" "${options[@]}" | rofi -dmenu -p "${prompt}" || error "Failed to get selection from GUI prompt")"
elif [[ -n "${WAYLAND_DISPLAY}" ]]; then
    selection="$(printf "%s\n" "${options[@]}" | hyprlauncher -p "${prompt}" || error "Failed to get selection from GUI prompt")"
else
    error "Environment not recognized."
fi

echo "${selection}"