#!/bin/bash

for cmd in curl jq; do
    if command -v "${cmd}" 1>/dev/null; then
        echo "Install '${cmd}'"
        exit 1
    fi
done

get_coordinates() {
    echo "Getting GPS coordinates..."
    coords="$(curl --fail http://ip-api.com/json?fields=lat,lon)"
    if [[ -n "${coords}" ]]; then
        latitude=$(echo "${coords}" | jq -r '.lat')
        longitude=$(echo "${coords}" | jq -r '.lon')
        echo "GPS coordinates obtained: ${latitude}, ${longitude}"
        echo -e "${latitude}\n${longitude}" > "${HOME}/.gps_coordinates"
    else
        echo "Failed to get GPS coordinates."
    fi
}

if [[ -f "${HOME}/.gps_coordinates" ]]; then
    echo "GPS coordinates file found. Reading GPS coordinates..."
    { IFS= read -r latitude; IFS= read -r longitude; } < "${HOME}/.gps_coordinates"
    echo "Current GPS coordinates: ${latitude}, ${longitude}"
else
    get_coordinates
fi