#!/bin/bash

folder="${1}"

if [[ -z "${folder}" ]]; then
    echo "No folder given"
    exit 1
elif [[ ! -d "${folder}" ]]; then
    echo "Folder not found: '${folder}'"
    exit 1
fi

folder_realpath="$(realpath "${folder}")"

m3u_file="${folder##*/}.m3u"

file_types=(
    -name "*.flac" -o
    -name "*.m4b" -o
    -name "*.mkv" -o
    -name "*.mp3" -o
    -name "*.mp4" -o
    -name "*.webm"
)

find_args=(
    "${folder_realpath}"
    -type f
    \( "${file_types[@]}" \)
)

readarray -t files < <(find "${find_args[@]}" | sort -V)
if (( "${#files[@]}" == 0 )); then
    echo "No media files found in the specified folder"
    exit 1
fi

printf "%s\n" "${files[@]}" > "${m3u_file}"