#!/bin/bash

folder="$(realpath "${1}")"
[[ -z "${folder}" || ! -d "${folder}" ]] && exit 1
m3u_name="$(basename "${folder}")"
file_types=(
    -name "*.flac" -o
    -name "*.m4b" -o
    -name "*.mkv" -o
    -name "*.mp3" -o
    -name "*.mp4" -o
    -name "*.webm"
)
readarray -t files < <(find "${folder}" -type f \( "${file_types[@]}" \) -exec realpath {} \; | sort -V)
[[ -z "${files[*]}" ]] && exit 1

printf "%s\n" "${files[@]}" > "${m3u_name}.m3u"