#!/bin/bash

catch() { echo "${1}"; exit 1; }

folder="$(realpath "${1}")"
[[ -d "${folder}" ]] || catch "Invalid folder path"
m3u_name="${folder##*/}"

file_types=(
    -name "*.flac" -o
    -name "*.m4b" -o
    -name "*.mkv" -o
    -name "*.mp3" -o
    -name "*.mp4" -o
    -name "*.webm"
)

readarray -t files < <(find "${folder}" -type f \( "${file_types[@]}" \) -exec realpath {} \; | sort -V || true)
[[ -z "${files[*]}" ]] && catch "No media files found in the specified folder"

printf "%s\n" "${files[@]}" > "${m3u_name}.m3u"