#!/bin/bash

nopass_file="/etc/sudoers.d/nopass"

if [[ -f "${nopass_file}" ]]; then
	echo "File already exists: '${nopass_file}'"
	exit 0
else
	sudo tee "${nopass_file}" <<- EOF
		%sudo ALL=(ALL) NOPASSWD: /usr/bin/apt-get
		%sudo ALL=(ALL) NOPASSWD: /usr/local/bin/apt
		%sudo ALL=(ALL) NOPASSWD: /usr/bin/gio
		%sudo ALL=(ALL) NOPASSWD: /usr/bin/dpkg
	EOF

	sudo chmod 440 "${nopass_file}"

	if [[ -f "${nopass_file}" ]]; then
		echo "File created: '${nopass_file}'"
		exit 0
	else
		echo "Failed to create '${nopass_file}'"
		exit 1
	fi
fi