#!/bin/bash

if ! command -v metaflac 1>/dev/null; then
    echo "Command not found: 'metaflac'"
    exit 1
fi

if (( "${#}" == 0 )); then
    echo "No songs given"
    exit 1
fi

for song in "${@}"; do
    if [[ ! -f "${song}" ]]; then
        echo "Song not found: '${song}'"
        continue
    fi

    echo -e "\n--==<[( ${song} )]>==--"

    album="$(metaflac --show-tag=ALBUM -- "${song}")"
    album_artist="$(metaflac --show-tag=ALBUMARTIST -- "${song}")"
    artist="$(metaflac --show-tag=ARTIST -- "${song}")"
    title="$(metaflac --show-tag=TITLE -- "${song}")"
    track_number="$(metaflac --show-tag=TRACKNUMBER -- "${song}")"

    album="${album##*=}"
    album_artist="${album_artist##*=}"
    artist="${artist##*=}"
    title="${title##*=}"
    track_number="${track_number##*=}"

	genre="Music"
	album="${album:-"NO_ALBUM"}"
    album_artist="${album_artist:-"NO_ALBUM_ARTIST"}"
    artist="${artist:-"NO_ARTIST"}"
    title="${title:-"NO_TITLE"}"
    track_number="${track_number:-"NO_TRACK_NUMBER"}"
    picture_file="picture.png"
	if [[ ! -f "${picture_file}" ]]; then
        convert -size 500x500 xc:black "${picture_file}"
	fi

    echo "  + Picture -> ${picture_file}"
    echo "  + Genre -> ${genre}"
    echo "  + Album -> ${album}"
    echo "  + Album Artist -> ${album_artist}"
    echo "  + Artist -> ${artist}"
    echo "  + Title -> ${title}"
    echo "  + Track Number -> ${track_number}"

	metaflac --remove-all -- "${song}"

	metaflac --set-tag=GENRE="${genre}" -- "${song}"
	metaflac --set-tag=ALBUM="${album}" -- "${song}"
	metaflac --set-tag=ALBUMARTIST="${album_artist}" -- "${song}"
	metaflac --set-tag=ARTIST="${artist}" -- "${song}"
	metaflac --set-tag=TITLE="${title}" -- "${song}"
	metaflac --set-tag=TRACKNUMBER="${track_number}" -- "${song}"
	if ! metaflac --import-picture-from="${picture_file}" "${song}" &>/dev/null; then
		echo "  - Could not import picture"
	fi

	filename="${album_artist//[^[:alnum:] \(\)\-]/} - ${title//[^[:alnum:] \(\)\-]/}.flac"
	if [[ ! -f "${filename}" ]]; then
        echo "  + ${song} -> ${filename}"
        mv -- "${song}" "${filename}"
    fi

    # this is completely unnecessary :)
    printf -v dashes "%*s" "${#song}" ""
    echo -e "--==<[( ${dashes// /-} )]>==--\n"
done
