#!/bin/bash

walls_dir="${HOME}/dotfiles/dot-walls"
walls=("${walls_dir}"/*.jpg "${walls_dir}"/*.jpeg "${walls_dir}"/*.png)
if (( ${#walls[@]} == 0 )); then
    echo "No walls found in '${walls_dir}'"
    exit 1
fi

for wall in "${walls[@]}"; do
    random_hex=$(openssl rand -hex 4)
    ext="${wall##*.}"
    new_file_name="${walls_dir}/${random_hex,,}.jpg"
    
    echo "${wall##*/} -> ${new_file_name}"
    if [[ "${ext}" == "png" ]]; then
        convert "${wall}" -quality 100 "${new_file_name}"
        rm -f "${wall}"
    else
        mv -n "${wall}" "${new_file_name}"
    fi
done
