#!/bin/bash

catch() { echo "${1}"; exit 1; }

[[ -f "${HOME}/.gps_coordinates" ]] || catch "GPS coordinates file not found. Run 'common-get-gpscoords' to get the GPS coordinates first."
{ IFS= read -r latitude; IFS= read -r longitude; } < "${HOME}/.gps_coordinates"
[[ -z "${latitude}" || -z "${longitude}" ]] && catch "Failed to get GPS coordinates."

gammastep_args=(
    -l "${latitude}:${longitude}"
    -b 1.0:0.6
    -t 6000:4000
    -m randr
)

pgrep -x gammastep && killall -q -w gammastep
gammastep "${gammastep_args[@]}" &
