#!/bin/bash

if ! command -v yay 1>/dev/null; then
    echo "Install 'yay'"
    exit 1
fi

if ! ping -qn -c 1 aur.archlinux.org &> /dev/null; then
    echo  "Cannot ping AUR"
    exit 1
fi

yay -Sua --noconfirm --cleanafter --ignore gcc14 --ignore gcc14-libs