#!/bin/bash

catch() { echo "${1}"; exit 1; }

command -v gammastep 1>/dev/null \
|| catch "Command not found: 'gammastep'"

[[ -f "${HOME}/.gps_coordinates" ]] \
|| catch "GPS coordinates file not found. Run 'common-get-gpscoords'."

{ IFS= read -r latitude; IFS= read -r longitude; } < "${HOME}/.gps_coordinates"
[[ -n "${latitude}" && -n "${longitude}" ]] \
|| catch "Failed to get GPS coordinates."

gammastep_args=(
    -l "${latitude}:${longitude}"
    -b 1.0:0.6
    -t 6000:4000
    -m randr
)

pgrep -x gammastep && killall -q -w gammastep
nohup gammastep "${gammastep_args[@]}" & disown
