#!/bin/bash

echo -e "\e[32mUpdate pacman packages\e[0m"

sudo pacman -Syyu

if [[ ! -d /usr/lib/modules/$(uname -r) ]]; then
    read -p "Kernel has been updated and needs a reboot. Reboot now? [y/N]: "
    if [[ "${REPLY:-NO}" =~ ^[Yy] ]]; then
        hyprctl dispatch exit
        while pgrep -x hyprland &>/dev/null; do
            sleep 0.1
        done
        systemctl reboot
    else
        echo "Please reboot as soon as possible to apply kernel updates."
        exit 0
    fi
fi