#!/bin/bash

catch() { echo "${1}"; exit 1; }

command -v hyprsunset 1>/dev/null \
|| catch "Command not found: 'hyprsunset'"

[[ -f "${HOME}/.gps_coordinates" ]] \
|| catch "GPS coordinates file not found. Run 'common-get-gpscoords'."

{ IFS= read -r latitude; IFS= read -r longitude; } < "${HOME}/.gps_coordinates"
[[ -n "${latitude}" && -n "${longitude}" ]] \
|| catch "Failed to get GPS coordinates."

hyprsunset_args=(
    -l "${latitude}:${longitude}"
)

pgrep -x hyprsunset && killall -q -w hyprsunset
nohup hyprsunset "${hyprsunset_args[@]}" & disown
