#!/bin/bash

chkcmd pacman

catch() { echo "${1}"; exit 1; }
confirm() { read -p "${1} [y/N]: "; [[ "${REPLY,,}" == "y" ]] || exit 1; }

echo -e "\e[32mUpdate pacman packages\e[0m"
sudo pacman -Syyu --noconfirm

[[ -d /usr/lib/modules/$(uname -r) ]] || confirm "Linux kernel has been updated. Reboot?" && hyrule-system-reboot
