#!/bin/bash

tv="$(wpctl status -n | grep "alsa_output.pci-0000_0d_00.6.analog-stereo" | grep -oE "[0-9]+" | head -1)"
desk="$(wpctl status -n | grep "easyeffects_sink" | grep -oE "[0-9]+" | head -1)"

usage() {
    echo "${0##*/} <tv|desk>"
    exit 1
}

case "${1}" in
    "tv" ) wpctl set-default "${tv}" ;;
    "desk" ) wpctl set-default "${desk}" ;;
    * ) usage ;;
esac