#!/bin/bash
set -euo pipefail

usage() {
    echo "Usage: ${0##*/} [-n] [OPTION]"
    echo
    echo "Options:"
    echo "  -n Skip confirmation prompts"
    echo "  -s Suspend"
    echo "  -l Logout"
    echo "  -r Reboot"
    echo "  -o Shutdown"
    echo "  -b Reboot into BIOS"
    echo "  -t Change bootmode: TTY"
    echo "  -g Change bootmode: Graphical"
    return 1
}

while getopts "nslrobtg" opt; do
    case "${opt}" in
        n ) skip_confirm="1" ;;
        s ) selected_option="Suspend" ;;
        l ) selected_option="Logout" ;;
        r ) selected_option="Reboot" ;;
        o ) selected_option="Shutdown" ;;
        b ) selected_option="Reboot into BIOS" ;;
        t ) selected_option="Change bootmode: TTY" ;;
        g ) selected_option="Change bootmode: Graphical" ;;
        * ) usage ;;
    esac
done

shift $((OPTIND - 1))
skip_confirm="${skip_confirm:-0}"

_graceful_window_close() {
    local term open_windows window_type
    term="$(xprop -root _NET_ACTIVE_WINDOW | awk '{print $NF}')"
    term="$(printf "0x%08x" "${term}")"
    readarray -t open_windows < <(wmctrl -l | grep -v "${term}" | awk '{print $1}')

    for open_window in "${open_windows[@]}"; do
        window_type=$(xprop -id "${open_window}" _NET_WM_WINDOW_TYPE | awk '{print $NF}')
        [[ "${window_type}" == "_NET_WM_WINDOW_TYPE_NORMAL" ]] || continue
        wmctrl -ic "${open_window}"
        while xprop -id "${open_window}" &>/dev/null; do
            sleep 0.1
        done
    done
}

_suspend() {
    (( skip_confirm )) || confirm -rofi "Are you sure you want to suspend?"
    systemctl suspend
}

_logout() {
    (( skip_confirm )) || confirm -rofi "Are you sure you want to log out?"
    _graceful_window_close
    session_id="$(loginctl session-status | awk 'NR==1{print $1}')"
    loginctl terminate-session "${session_id}"
}

_reboot() {
    (( skip_confirm )) || confirm -rofi "Are you sure you want to reboot?"
    _graceful_window_close
    systemctl reboot
}

_shutdown() {
    (( skip_confirm )) || confirm -rofi "Are you sure you want to shut down?"
    _graceful_window_close
    systemctl poweroff
}

_reboot_bios() {
    (( skip_confirm )) || confirm -rofi "Are you sure you want to reboot into BIOS?"
    _graceful_window_close
    systemctl reboot --firmware-setup
}

_bootmode_tty() {
    (( skip_confirm )) || confirm -rofi "Change bootmode to TTY?"
    pkexec systemctl set-default multi-user.target
    selopt -rofi "Bootmode changed to TTY" "Ok"
}

_bootmode_graphical() {
    (( skip_confirm )) || confirm -rofi "Change bootmode to Graphical?"
    pkexec systemctl set-default graphical.target
    selopt -rofi "Bootmode changed to Graphical" "Ok"
}

options=(
    "Suspend"
    "Logout"
    "Reboot"
    "Shutdown"
    "Reboot into BIOS"
    "Change bootmode: TTY"
    "Change bootmode: Graphical"
)

if [[ -z "${selected_option:-}" ]]; then
    selected_option="$(selopt -rofi "Select an action:" "${options[@]}" || catch -i)"
fi

case "${selected_option}" in
    "Suspend"|"-s" ) _suspend ;;
    "Logout"|"-l" ) _logout ;;
    "Reboot"|"-r" ) _reboot ;;
    "Shutdown"|"-o" ) _shutdown ;;
    "Reboot into BIOS"|"-b" ) _reboot_bios ;;
    "Change bootmode: TTY"|"-t" ) _bootmode_tty ;;
    "Change bootmode: Graphical"|"-g" ) _bootmode_graphical ;;
    * ) usage ;;
esac
