#!/bin/bash

catch() { echo "${1}"; exit 1; }

command -v redshift 1>/dev/null \
|| catch "Command not found: 'redshift'"

[[ -f "${HOME}/.gps_coordinates" ]] \
|| catch "GPS coordinates file not found. Run 'gpscoords'."

{ IFS= read -r latitude; IFS= read -r longitude; } < "${HOME}/.gps_coordinates"
[[ -n "${latitude}" && -n "${longitude}" ]] \
|| catch "Failed to get GPS coordinates."

redshift_args=(
    -l "${latitude}:${longitude}"
    -b 1.0:0.6
    -t 6000:4000
    -m randr
)

pgrep -x redshift 1>/dev/null && killall -q -w redshift
nohup redshift "${redshift_args[@]}" & disown