#!/bin/bash
set -euo pipefail

launcher="-rofi"

_graceful_window_close() {
    local term open_windows window_type
    term="$(xprop -root _NET_ACTIVE_WINDOW | awk '{print $NF}')"
    term="$(printf "0x%08x" "${term}")"
    readarray -t open_windows < <(wmctrl -l | grep -v "${term}" | awk '{print $1}')

    for open_window in "${open_windows[@]}"; do
        window_type=$(xprop -id "${open_window}" _NET_WM_WINDOW_TYPE | awk '{print $NF}')
        [[ "${window_type}" == "_NET_WM_WINDOW_TYPE_NORMAL" ]] || continue
        wmctrl -ic "${open_window}"
        while xprop -id "${open_window}" &>/dev/null; do
            sleep 0.2
        done
    done
}

_suspend() {
    confirm "${launcher}" "Are you sure you want to suspend?"
    systemctl suspend
}

_logout() {
    confirm "${launcher}" "Are you sure you want to log out?"
    _graceful_window_close
    session_id="$(loginctl session-status | awk 'NR==1{print $1}')"
    loginctl terminate-session "${session_id}"
}

_reboot() {
    confirm "${launcher}" "Are you sure you want to reboot?"
    _graceful_window_close
    systemctl reboot
}

_shutdown() {
    confirm "${launcher}" "Are you sure you want to shut down?"
    _graceful_window_close
    systemctl poweroff
}

_reboot_bios() {
    confirm "${launcher}" "Are you sure you want to reboot into BIOS?"
    _graceful_window_close
    systemctl reboot --firmware-setup
}

_bootmode_tty() {
    confirm "${launcher}" "Change bootmode to TTY?"
    pkexec systemctl set-default multi-user.target
    selopt "${launcher}" "Bootmode changed to TTY" "Ok"
}

_bootmode_graphical() {
    confirm "${launcher}" "Change bootmode to Graphical?"
    pkexec systemctl set-default graphical.target
    selopt "${launcher}" "Bootmode changed to Graphical" "Ok"
}

options=(
    "Suspend"
    "Logout"
    "Reboot"
    "Shutdown"
    "Reboot into BIOS"
    "Change bootmode: TTY"
    "Change bootmode: Graphical"
)

selected_option="$(selopt "${launcher}" "Select an action:" "${options[@]}" || catch -i "No option selected")"
case "${selected_option}" in
    "Suspend") _suspend ;;
    "Logout") _logout ;;
    "Reboot") _reboot ;;
    "Shutdown") _shutdown ;;
    "Reboot into BIOS") _reboot_bios ;;
    "Change bootmode: TTY") _bootmode_tty ;;
    "Change bootmode: Graphical") _bootmode_graphical ;;
    *) exit 1 ;;
esac
