#!/bin/bash
set -e

echo -e "\e[32mUpdate pacman packages\e[0m"
sudo pacman -Syyu --noconfirm

[[ -d /usr/lib/modules/$(uname -r) ]] || common-util-confirm "Linux kernel has been updated. Reboot?" && hyrule-system-reboot
