#!/bin/bash

sdown_time="${1}"
if [[ -z "${sdown_time}" ]]; then
	echo "Must enter a time to shutdown"
	exit 1
fi

sdown_time_epoch="$(date -d "${sdown_time}" +%s)"
current_time_epoch="$(date +%s)"

if (( "${sdown_time_epoch}" < "${current_time_epoch}" )); then
	sdown_time_epoch="$(date -d "tomorrow ${sdown_time}" +%s)"
fi

sdown_time_minutes="$(( ( "${sdown_time_epoch}" - "${current_time_epoch}" ) / 60 ))"

sudo shutdown +${sdown_time_minutes}
