#!/bin/bash

chkcmd yt-dlp || exit 1

if [[ "${1:-}" == "a" ]]; then
    is_audio=0
    shift # remove the first option from argument list
elif [[ "${1:-}" == "720" || "${1:-}" == "1080" ]]; then
    is_audio=1
    resolution="${1:-1080}"
    shift  # remove the first option from argument list
fi

urls=("${@}")
if [[ -z "${urls[*]}" ]]; then
    echo "usage: ${0} [1080 (default)|720|a] [url]|[url2 url3 etc]"
    exit 1
fi

ytdlp_options=(
    -N8
    --restrict-filenames
    --sponsorblock-mark all
    -S "res:${resolution:-1080}"
    -o "${HOME}/Videos/%(uploader|Unknown)s - %(upload_date>%m%d)s - %(title)s.%(ext)s"
)

ytdlp_audio_options=(
    -N8
    -x
    -o "${HOME}/Music/unprocessed-files/%(uploader|Unknown)s - %(title)s.%(ext)s"
)

if (( "${is_audio:-1}" )); then
    yt-dlp "${ytdlp_audio_options[@]}" "${urls[@]}"
else
    yt-dlp "${ytdlp_options[@]}" "${urls[@]}"
fi