<<<<<<< HEAD
#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox
=======
#######################
###### AUTOSTART ######
#######################

exec-once = waybar & 
exec-once = hyprpaper &
>>>>>>> 03f08e2d41ca33f82aba0c47a2a2b3c9a4bd66a3
