<<<<<<< HEAD
#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hypr.land/Configuring/Environment-variables/
=======
###################################
###### ENVIRONMENT VARIABLES ######
###################################
>>>>>>> 03f08e2d41ca33f82aba0c47a2a2b3c9a4bd66a3

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24