#############################
###### HYPRLAND CONFIG ######
#############################

<<<<<<< HEAD
source ~/.config/hypr/monitors.conf
source ~/.config/hypr/programs.conf
source ~/.config/hypr/autostart.conf
source ~/.config/hypr/envvars.conf
source ~/.config/hypr/permissions.conf
source ~/.config/hypr/lookfeel.conf
source ~/.config/hypr/input.conf
source ~/.config/hypr/keybinds.conf
source ~/.config/hypr/windows.conf
=======
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/programs.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/envvars.conf
source = ~/.config/hypr/permissions.conf
source = ~/.config/hypr/lookfeel.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/windows.conf
>>>>>>> 03f08e2d41ca33f82aba0c47a2a2b3c9a4bd66a3
