<<<<<<< HEAD
################
### PROGRAMS ###
################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = dolphin
$menu = wofi --show drun
=======
######################
###### PROGRAMS ######
######################

$terminal = alacritty
$filemanager = thunar
$menu = fuzzel
>>>>>>> 03f08e2d41ca33f82aba0c47a2a2b3c9a4bd66a3

