#! /bin/sh

pgrep -x sxhkd 1> /dev/null || sxhkd &
pgrep -x polybar 1> /dev/null || polybar &
pgrep -x picom 1> /dev/null || picom &
command -v setwall 1> /dev/null && setwall

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 2
bspc config window_gap 12

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off