#!/bin/bash

catch() { echo -e "\e[31m${1}\e[0m"; exit 1; }

command -v lutgen &>/dev/null || catch "Install 'lutgen'"

walls_dir="${HOME}/dotfiles/dot-walls"
[[ -d "${walls_dir}" ]] || catch "Walls directory does not exist."

original_walls_dir="${walls_dir}/original"
[[ -d "${original_walls_dir}" ]] || catch "Original walls directory does not exist."

_lutgen_wall() {
    local scheme scheme_dir wall wall_no_path wall_no_ext output_name
    scheme="${1}"
    scheme_dir="${walls_dir}/${scheme}"
    shopt -s nullglob nocaseglob
    original_walls=("${original_walls_dir%/}/"*.jpg)
    shopt -u nullglob nocaseglob
    lutgen_args=(
        "-R"
        "-P"
        "-L"
        "1.2"
        "--level"
        "16"
    )

    [[ -n "${scheme}" ]] || catch "Usage: ${FUNCNAME} [scheme]"
    mkdir -p "${scheme_dir}" || catch "Failed to create directory '${scheme_dir}'."
    [[ ${#original_walls[@]} -eq 0 ]] && catch "No files found in '${original_walls_dir}' directory."
    
    for wall in "${original_walls[@]}"; do
        wall_no_path="${wall##*/}"
        wall_no_ext="${wall_no_path%.*}"
        output_name="${scheme_dir}/${wall_no_ext}-${scheme}.png"
        if [[ ! -e "${output_name}" ]]; then
            echo -e "\e[32mGenerating wall for scheme '${scheme}' from ${wall}\e[0m"
            lutgen apply "${lutgen_args[@]}" -p "${scheme}" "${wall}" --output="${output_name}" 1>/dev/null ||\
                catch "Failed to generate wall for scheme '${scheme}' from ${wall}."
        else
            echo -e "\e[33mWall '${wall_no_path}' already exists in '${scheme}' directory.\e[0m"
            continue
        fi
    done
}

schemes=(
    catppuccin-mocha
    nord
    gruvbox-dark
)

for scheme in "${schemes[@]}"; do
    _lutgen_wall "${scheme}"
done