#!/bin/bash

chkcmd lutgen || exit 1

catch() {echo -e "\e[31m${1}\e[0m"; exit 1; }
catch_continue() {echo -e "\e[33m${1}\e[0m"; continue; }

original_walls_dir="${HOME}/dotfiles/dot-walls/original"
[[ -d "${original_walls_dir}" ]] || catch "Original walls directory does not exist."

_lutgen_wall() {
    local scheme scheme_dir wall
    scheme="${1}"
    scheme_dir="${original_walls_dir}/${scheme}"
    [[ -n "${scheme}" ]] || catch "Usage: ${FUNCNAME} [scheme]"
    [[ -d "${scheme_dir}" ]] || mkdir -p "${scheme_dir}" || catch "Failed to create directory for scheme '${scheme}'."
    
    shopt -s nullglob
    original_walls=("${original_walls_dir}"/*)
    shopt -u nullglob
    [[ ${#original_walls[@]} -eq 0 ]] && catch "No files found in '${original_walls_dir}' directory."
    
    for wall in "${original_walls_dir}"/*; do
        if [[ ! -e "${scheme_dir}/${wall##*/}" ]]; then
            echo -e "\e[32mGenerating wall for scheme '${scheme}' from ${wall}...\e[0m"
            output_name="${scheme_dir}/${wall##*/}-${scheme}.jpg"
            lutgen apply --preserve -p "${scheme}" "${wall}" "${output_name}" ||\
                catch "Failed to generate wall for scheme '${scheme}' from ${wall}."
        else
            catch_continue "Wall '${wall##*/}' already exists in '${scheme}' directory."
        fi
    done
}

schemes=(
    catppuccin-mocha
    nord
    gruvbox-dark
)

for scheme in "${schemes[@]}"; do
    _lutgen_wall "${scheme}"
done