#!/bin/bash

source functions || exit 1

for file in "${HOME}/.scripts"/*; do
    [[ -f "${file}" ]] || continue
    if head -n 1 "${file}" | grep -q '^#!/bin/bash$'; then
        echo "Making ${file} executable..."
        chmod +x "${file}" || alert "Failed to make '${file}' executable."
    fi
done