#!/bin/bash

fzf_args=(
    --color "pointer:green,marker:green"
    --exact
    --multi
    --preview-label-pos="bottom"
    --preview-label="tab: multi-select"
    --preview "pacman -Sii {1}"
    --preview-window "down:60%:wrap"
)

pacman -Slq | fzf "${fzf_args[@]}" | xargs -r sudo pacman -S --noconfirm
sudo updatedb
