#!/bin/bash

error() { echo "${1}"; exit 1; }

wall_dir="${HOME}/.walls"
if [[ -d "${wall_dir}" ]]; then
    shopt -s globstar nullglob
    files=("${wall_dir}"/**/*.jpg)
    shopt -u globstar nullglob
else
    error "'${wall_dir}' does not exist"
fi

if [[ -n "${files[*]}" ]]; then
    wall="${files[RANDOM % ${#files[@]}]}"
else
    error "No '.jpg' files found in '${wall_dir}'"
fi

case "${XDG_SESSION_TYPE}" in
    wayland) command -v swaybg && swaybg -i "${wall}" & ;;
    x11) command -v feh && feh --bg-scale "${wall}" & ;;
    tty) : ;;
    *) error "Unknown session type: ${XDG_SESSION_TYPE}" ;;
esac
