#!/bin/bash
set -euo pipefail


! command -v fzf && sudo apt-get install -y -- fzf


options=(
    "TTY"
    "Cinnamon"
)


fzf_options=(
    -e
    --reverse
)


tty_boot() {
    sudo systemctl set-default multi-user.target
    echo "press enter to reboot into tty mode..."
    read
    sudo reboot
}


cinnamon_boot() {
    sudo sudo systemctl set-default graphical.target
    echo "press enter to reboot into graphical mode..."
    read
    sudo reboot
}


selected_option="$(printf "%s\n" "${options[@]}" | fzf "${fzf_options[@]}")"
case "${selected_option}" in
    "TTY") tty_boot ;;
    "Cinnamon") cinnamon_boot ;;
    *) exit 1 ;;
esac


####
