#!/bin/bash

if command -v apt-get; then
    sudo apt-get update
    sudo apt-get upgrade -y
elif command -v pacman; then
    sudo pacman -Syu --noconfirm
    command -v yay && yay -Syu --noconfirm
fi

command -v flatpak && flatpak update --noninteractive